import type { Locale } from "@/i18n/config";

const tw = {
  title: "興毅永續行動",
  tagline: "惜食有愛，幸福共好",
  teaser: "讓仍可安心食用、正常使用的食品與生活物資延續價值，重新流向真正需要的地方。",
  learnMore: "了解永續行動",
  intro: [
    "有些食品與生活物資，並不是失去價值，只是因為即將屆期、庫存過多、包裝改版、訂單取消、活動結束或其他原因，不再適合繼續販售或留存。",
    "「興毅永續行動」希望串聯個人、店家、工廠、企業及各界夥伴，將這些「用不到，但仍可安心食用或正常使用」的物資留下來，由興毅基金會依物資狀況進行接收、整理、保存與分配，讓資源重新流向真正需要的地方。",
    "我們希望減少的不只是食物浪費，也包含生活物資的閒置與報廢。讓原本可能被丟棄的資源延續價值，也讓每一份物資成為支持弱勢家庭與社區的一份力量。",
  ],
  scopeNote: "「興毅永續行動」主要針對剩餘、閒置、庫存、短效期或其他可能被浪費的食品與生活物資。",
  foodbankNote: "若您希望購買食品、日用品捐贈，或定期提供食物銀行日常所需物資，請前往「忠信食物銀行」頁面。",
  suppliesTitle: "哪些物資適合提供？",
  supplies: [
    {
      title: "食品類",
      items: ["即將屆期，但仍可安全食用的食品", "門市下架，但仍符合食用安全的食品", "庫存過多的商品", "更換包裝或規格後的商品", "訂單取消所產生的庫存", "生產數量超出需求的食品", "節慶、活動結束後剩餘的完整商品", "其他仍可安心食用，但可能面臨報廢或丟棄的食品"],
      notes: ["食品原則上應包裝完整、保存正常、標示清楚，且未逾有效期限。", "短效期食品為避免寄送時間過長，原則上至少須保留 20 天以上效期。", "若為大量物資、冷藏、冷凍、生鮮食品或其他特殊品項，請先與本會聯繫，由工作人員依種類、數量、效期、保存方式、運送距離及實際分配能力進行評估。"],
    },
    {
      title: "生活物資",
      items: ["洗髮精、沐浴乳", "洗衣精、洗碗精及其他清潔用品", "衛生紙", "成人及嬰幼兒尿布", "家庭日常用品", "包裝改版後的商品", "規格更換後的庫存品", "活動或專案結束後剩餘的新品", "長期未使用，但仍全新且可正常使用的庫存", "其他可能被閒置或報廢的生活物資"],
      notes: ["生活物資應為可正常使用、包裝及標示完整，並符合安全使用原則。", "實際是否接收，將依物資品項、數量、保存狀況、效期、運送方式及各據點實際承接能力進行確認。"],
    },
  ],
  recipientsTitle: "收到的物資會分享給誰？",
  recipientsIntro: "本會收到物資後，會依物資種類、數量、效期、保存方式及實際需求，進行確認、分類、保存與分配。",
  recipients: [
    { title: "忠信食物銀行會員", description: "提供給經本會審核通過的食物銀行會員家庭，補充食品、清潔用品、衛生用品及其他生活所需，協助減輕家庭日常生活負擔。" },
    { title: "其他社福單位", description: "對於數量較多、規格特殊，或適合特定服務對象使用的物資，本會將依實際需求分享給合作的社福團體及服務機構，支持兒少、長者、身心障礙者及弱勢家庭等服務。" },
    { title: "照顧弱勢家庭的里長", description: "本會也與長期投入社區弱勢照顧的里長及在地服務網絡合作，協助社區中經濟困難、突遭變故，或尚未進入正式福利服務體系的家庭。" },
  ],
  flowTitle: "讓剩餘資源形成善的循環",
  flow: ["可能被閒置、報廢或丟棄的物資", "興毅基金會接收與確認", "分類、保存與需求媒合", "食物銀行會員／社福單位／社區服務網絡", "物資重新被使用，延續資源價值"],
  flowNote: "我們希望建立的不只是一次性的物資轉贈，而是一個能持續串聯捐贈端與需求端的資源分享網絡。",
  valuesTitle: "每一份物資，都能創造更多價值",
  values: [
    { title: "珍惜資源", description: "延續食品與生活物資的生命週期，減少不必要的浪費與報廢。" },
    { title: "善的循環", description: "將原本用不到或沒有去處的物資，轉化為另一個家庭或服務單位真正需要的資源。" },
    { title: "社會韌性", description: "讓資源進入不同的弱勢支持系統，增加社區面對困難與突發事件時的支持力量。" },
    { title: "永續未來", description: "讓個人、店家、工廠及企業透過資源分享參與永續行動，創造環境與社會價值。" },
  ],
  situationsTitle: "哪些情況適合與我們聯繫？",
  situations: ["門市有即將屆期，但仍可安全食用的食品", "工廠有生產餘量或訂單取消後的庫存", "商品因包裝改版、規格更換而停止販售", "倉庫有庫存過多或不再使用，但仍可正常使用的物資", "公司有活動、節慶或專案結束後剩餘的商品或物資", "希望減少產品報廢、銷毀或閒置", "希望建立固定的惜食、庫存或剩餘物資合作機制", "希望透過物資分享落實 ESG、永續或公益行動"],
  situationsNote: "無論是單次、不定期提供，或希望建立長期合作機制，都歡迎先與本會討論。",
  infoTitle: "提供物資前，請先告訴我們",
  infoItems: ["物資名稱及品項", "數量或箱數", "有效期限（如有）", "保存方式（常溫／冷藏／冷凍）", "物資目前所在地", "預計可提供的時間", "物資照片"],
  infoNote: "本會將依物資狀況評估接收方式，再與您確認後續送達、寄送或取貨安排。大量物資、冷藏冷凍食品、生鮮食品及短效期物資，請務必先聯繫，確認後再安排運送。",
  partnersTitle: "永續合作夥伴",
  partnersText: "感謝願意將剩餘資源轉化為公益力量的個人、店家、工廠與企業。合作夥伴 LOGO 將陸續於此公布。",
  joinTitle: "一起加入興毅永續行動",
  joinText: "有些物資只是用不到，不代表沒有人需要。讓我們一起珍惜資源、延續物資價值，也讓這份資源成為另一個家庭需要的支持。",
  provide: "我有物資可以提供",
  cooperate: "洽談永續合作",
  contact: "聯絡我們",
  formNote: "填寫後將由網站直接寄送至興毅基金會；物資照片可一併附加（JPG／PNG／WebP，最大 5 MB）。",
  partnershipFormNote: "填寫後將由網站直接寄送合作需求至興毅基金會。",
  submit: "直接送出",
  fields: { name: "姓名／公司名稱", phone: "聯絡電話", email: "Email", item: "物資名稱及品項", quantity: "數量或箱數", expiry: "有效期限（如有）", storage: "保存方式", location: "物資目前所在地", available: "預計可提供的時間", photo: "物資照片", message: "合作需求／留言" },
} as const;

const en = {
  ...tw,
  title: "Shing Yi Sustainability Action",
  tagline: "Save Resources, Share Happiness",
  teaser: "Give safe food and usable daily essentials a longer life by redirecting them to people and communities that need them.",
  learnMore: "Explore the Initiative",
  intro: [
    "Food and daily essentials do not lose their value simply because they are approaching their best-before date, overstocked, repackaged, left after a cancelled order, or no longer needed after an event.",
    "Shing Yi Sustainability Action connects individuals, shops, factories, businesses, and community partners. We receive, sort, store, and distribute safe, usable surplus goods so they can reach people who truly need them.",
    "Our goal is to reduce not only food waste, but also the unnecessary disposal of daily essentials—extending the value of every resource while supporting vulnerable families and communities.",
  ],
  scopeNote: "This initiative focuses on surplus, idle, overstocked, short-dated, or otherwise usable food and daily essentials that may go to waste.",
  foodbankNote: "To purchase food or daily necessities for regular donation, please visit the Zhongxin Food Bank page.",
  suppliesTitle: "What Can You Provide?",
  supplies: [
    { title: "Food", items: ["Short-dated food that remains safe to eat", "Products removed from shelves but still safe", "Overstocked products", "Products with replaced packaging or specifications", "Inventory from cancelled orders", "Production surplus", "Complete goods left after festivals or events", "Other safe food at risk of disposal"], notes: ["Food should be properly packaged and stored, clearly labeled, and within its valid date.", "Short-dated food should generally have at least 20 days remaining.", "Contact us first for large quantities, chilled, frozen, fresh, or other special items so we can assess storage, transport, and distribution capacity."] },
    { title: "Daily Essentials", items: ["Shampoo and body wash", "Laundry, dishwashing, and cleaning supplies", "Tissue paper", "Adult and infant diapers", "Household necessities", "Products with updated packaging", "Inventory after specification changes", "New goods left after events or projects", "Unused, new, and functional inventory", "Other usable goods at risk of disposal"], notes: ["Goods must be safe and functional, with complete packaging and labels.", "Acceptance depends on the item, quantity, condition, shelf life, transport, and capacity of each service location."] },
  ],
  recipientsTitle: "Who Receives the Supplies?",
  recipientsIntro: "We assess, sort, store, and distribute supplies according to type, quantity, shelf life, storage requirements, and actual need.",
  recipients: [
    { title: "Zhongxin Food Bank Members", description: "Approved member households receive food, cleaning products, hygiene supplies, and other daily essentials, helping ease the burden of everyday living." },
    { title: "Social Welfare Organizations", description: "Large, specialized, or audience-specific supplies are shared with partner organizations according to actual needs, supporting children, older adults, people with disabilities, and vulnerable families." },
    { title: "Local Leaders Supporting Families", description: "We work with local leaders and community networks committed to vulnerable families, reaching households facing financial hardship, sudden crises, or those not yet connected to formal welfare services." },
  ],
  flowTitle: "Creating a Cycle of Good",
  flow: ["Usable goods at risk of waste", "Received and assessed by Shing Yi Foundation", "Sorted, stored, and matched to needs", "Food bank members, welfare organizations, and communities", "Resources reused and value extended"],
  flowNote: "We are building more than one-time transfers: a lasting network connecting surplus resources with real needs.",
  valuesTitle: "Every Resource Creates More Value",
  values: [
    { title: "Resource Care", description: "Extend product life cycles and reduce unnecessary waste." },
    { title: "A Cycle of Good", description: "Turn unused goods into resources another family or organization genuinely needs." },
    { title: "Community Resilience", description: "Strengthen support networks for households facing hardship and emergencies." },
    { title: "A Sustainable Future", description: "Enable individuals and businesses to create environmental and social value through sharing." },
  ],
  situationsTitle: "When Should You Contact Us?",
  situations: ["A shop has short-dated but safe food", "A factory has production surplus or cancelled-order inventory", "Products are discontinued after packaging or specification changes", "A warehouse holds usable excess inventory", "Goods remain after an event, festival, or project", "You want to reduce disposal or idle inventory", "You want a recurring surplus-goods partnership", "You want to put ESG or community commitments into action"],
  situationsNote: "Whether the contribution is one-time, occasional, or a long-term partnership, contact us first to discuss the best arrangement.",
  infoTitle: "Tell Us Before Providing Supplies",
  infoItems: ["Item name and type", "Quantity or number of cartons", "Expiration date, if applicable", "Storage method: ambient, chilled, or frozen", "Current location", "Available date", "Photos"],
  infoNote: "We assess each offer before confirming delivery, shipping, or collection. Please contact us before transporting large quantities, chilled or frozen food, fresh food, or short-dated items.",
  partnersTitle: "Sustainability Partners",
  partnersText: "We thank every individual, shop, factory, and business that turns surplus resources into community support. Partner logos will be published here over time.",
  joinTitle: "Join Shing Yi Sustainability Action",
  joinText: "Something you no longer need may be exactly what another family needs. Together, we can protect resources, extend their value, and transform them into practical support.",
  provide: "I Have Supplies to Offer",
  cooperate: "Discuss a Partnership",
  contact: "Contact Us",
  formNote: "The website will send this form directly to Shing Yi Foundation. You may attach one JPG, PNG, or WebP photo up to 5 MB.",
  partnershipFormNote: "The website will send your partnership request directly to Shing Yi Foundation.",
  submit: "Send",
  fields: { name: "Name / Company", phone: "Phone", email: "Email", item: "Item name and type", quantity: "Quantity / Cartons", expiry: "Expiration date, if applicable", storage: "Storage method", location: "Current location", available: "Available date", photo: "Supply photos", message: "Partnership needs / Message" },
} as const;

export function getSustainabilityActionContent(locale: Locale) {
  return locale === "en" ? en : tw;
}
